version: "3.9"
services:
  app_a:
    build: ./app_a
    ports:
      - "8000:8000"
    depends_on:
      - app_b

  app_b:
    build: ./app_b
    ports:
      - "8010:8000"
  
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4317:4317"
      - "4318:4318"

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "9411:9411"    # Zipkin endpoint

